<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>plugin_test2</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <UseWinUI>true</UseWinUI>
    <NoWarn>MSB3277</NoWarn>
    <!-- Nuget -->
    <PackageId>ACOMPlug.Widget.Slide</PackageId>
    <Version>1.0.0.12</Version>
    <!-- PluginMeta -->
    <PluginMeta>
      <!-- 使用上文的PackageId变量 -->
      <Id>$(PackageId)</Id>
      <Name>emoji</Name>
      <Version>$(Version)</Version>
      <Author>kitUIN</Author>
    </PluginMeta>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="WidgetSlide.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
    <PackageReference Include="ShadowPluginLoader.MetaAttributes" Version="1.1.2" />
    <PackageReference Include="ShadowPluginLoader.WinUI" Version="1.3.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ACOMPlugin\ACOMPlugin.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="WidgetSlide.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist &quot;$(ProjectDir)..\Packages\$(ProjectName)&quot; mkdir &quot;$(ProjectDir)..\Packages\$(ProjectName)&quot;&#xD;&#xA;xcopy /e &quot;$(TargetDir)&quot; &quot;$(ProjectDir)..\Packages\$(ProjectName)&quot; /Y " />
  </Target>
  
</Project>