// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace ACOMv2;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"ACOMv2.Views.DeviceConnect.SerialConnect", typeof(ACOMv2.Views.DeviceConnect.SerialConnect)},
        {"ACOMv2.Views.DeviceConnect.TCPConnect", typeof(ACOMv2.Views.DeviceConnect.TCPConnect)},
        {"ACOMv2.Views.DeviceConnect.Parts", typeof(ACOMv2.Views.DeviceConnect.Parts)},
    };
}
