global using ACOM.Common;
global using ACOM.ViewModels;
global using ACOM.Views;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using WinUICommunity;
global using static ACOM.Common.AppHelper;
global using static ACOM.Common.LoggerSetup;
